FROM maven:3.6.1-jdk-11-slim
WORKDIR /home/azureuser/workspace/DevOps/community/build/poms/
CMD ["mvn","clean","install"]

FROM maven:3.6.1-jdk-11-slim
WORKDIR /home/azureuser/workspace/DevOps/
COPY  community/ant/lib/*.jar /target/
EXPOSE 8080
ENTRYPOINT ["java","-jar","logicaldoc-1.0-SNAPSHOT.jar"]


